"""Complete, bounded EN/PL copy for the public guided journey."""

COPY = {
    "en": {
        "DRAFT": "Draft",
        "SUBMITTED": "Awaiting review",
        "APPROVED": "Approved",
        "REJECTED": "Rejected",
        "title": "A decision needs more than a chat message.",
        "intro": "Try a real approval workflow: propose a change, review it as another person, and inspect the recorded decision.",
        "scope": "Independent working demonstration. Synthetic people and requests. No external business operation is performed.",
        "limits": "Your isolated workspace expires after 20 minutes. Use synthetic text only; do not enter personal or confidential data. Free hosting may take about a minute to wake up.",
        "start": "Start my private demo",
        "restart": "Start a fresh scenario",
        "restart_note": "The previous workspace expires immediately and is removed on cleanup.",
        "roles": "View as a synthetic participant",
        "requester": "Requester",
        "reviewer": "Reviewer",
        "second_reviewer": "Second reviewer",
        "auditor": "Auditor · read only",
        "guide": "Three things to verify",
        "steps": [
            "Submit the proposed change as requester.",
            "Switch to reviewer and approve or reject it.",
            "Inspect the history and download evidence. Try an old version: it must not overwrite the decision.",
        ],
        "state": "State",
        "version": "Version",
        "reason": "Reason for this action",
        "title_label": "Proposed change",
        "proposal": "What should change?",
        "edit": "Save draft",
        "submit": "Submit for review",
        "approve": "Approve",
        "reject": "Reject",
        "revise": "Return to draft",
        "history": "Decision history",
        "export": "Download evidence JSON",
        "stale": "Try a decision from the earlier version",
        "stale_note": "An actual command using the submitted version. After a decision, the server must reject it without adding an event.",
        "closed": "This decision is closed. Inspect the evidence or start a fresh scenario.",
        "readonly": "This role can inspect and export evidence, but cannot change the request.",
        "switch_hint": "Switch to the other participant to continue. Permissions are checked on the server.",
        "saved": "The server recorded the action.",
        "replayed": "Same command, same receipt. No second event was created.",
        "error": "The action was not confirmed",
        "back": "Return to the current request",
        "retry": "Retry the same command",
        "retained": "Your submitted text is retained below. Review it before retrying. A stale version needs a fresh review, not a blind retry.",
        "unknown": "The database response was unavailable. The outcome may be unknown. Retry the same command key; do not create a new command.",
        "expired": "This temporary workspace has expired. Start a fresh synthetic scenario.",
        "quota": "The demo has reached a temporary safety limit. Please try again later.",
        "default_title": "Route unmatched billing updates to review",
        "default_proposal": "Synthetic scenario: billing updates without a customer match should enter an exception queue. An operator checks the mapping before any update is approved. This desk records the decision; it does not connect to a billing system.",
        "default_reason": "Check the synthetic routing change before approving it.",
        "source": "Source code and reproducible tests",
        "next": "Have a workflow that is hard to control?",
        "contact": "Describe your problem",
        "receipt": "Server receipt",
        "expiry": "Workspace expires",
        "codes": {
            "STALE_VERSION": "Another decision already changed this version. Your action did not overwrite it.",
            "READ_ONLY_ROLE": "The auditor cannot modify a request.",
            "REVIEWER_REQUIRED": "A different participant with the reviewer role must make this decision.",
            "SELF_REVIEW_FORBIDDEN": "A requester cannot approve their own change.",
            "INVALID_TRANSITION": "This action is not allowed in the current state.",
            "REASON_REQUIRED_10_TO_500": "Provide a reason between 10 and 500 characters.",
            "INVALID_TITLE": "The title must contain 5–120 characters.",
            "INVALID_PROPOSAL": "The proposal must contain 5–4000 characters.",
            "INVALID_COMMAND": "The request could not be validated.",
            "NOT_FOUND": "This request is not available in your workspace.",
            "COMMAND_KEY_CONFLICT": "This command key already belongs to different content.",
        },
    },
    "pl": {
        "DRAFT": "Szkic",
        "SUBMITTED": "Do oceny",
        "APPROVED": "Zatwierdzone",
        "REJECTED": "Odrzucone",
        "title": "Decyzja wymaga czegoś więcej niż wiadomości na czacie.",
        "intro": "Sprawdź działający proces akceptacji: zaproponuj zmianę, oceń ją jako druga osoba i prześledź zapisaną decyzję.",
        "scope": "Niezależna działająca demonstracja. Fikcyjne osoby i zgłoszenia. Żadna operacja w zewnętrznym systemie biznesowym nie jest wykonywana.",
        "limits": "Twoje odizolowane środowisko wygasa po 20 minutach. Używaj wyłącznie fikcyjnych treści, bez danych osobowych i poufnych. Bezpłatny serwer może potrzebować około minuty na uruchomienie.",
        "start": "Uruchom moje prywatne demo",
        "restart": "Rozpocznij nowy scenariusz",
        "restart_note": "Poprzednie środowisko natychmiast wygasa i zostaje usunięte podczas sprzątania.",
        "roles": "Zobacz jako fikcyjny uczestnik",
        "requester": "Wnioskodawca",
        "reviewer": "Osoba zatwierdzająca",
        "second_reviewer": "Druga osoba zatwierdzająca",
        "auditor": "Audytor · tylko odczyt",
        "guide": "Trzy rzeczy do sprawdzenia",
        "steps": [
            "Przekaż propozycję do oceny jako wnioskodawca.",
            "Zmień rolę i zatwierdź lub odrzuć propozycję.",
            "Sprawdź historię i pobierz raport. Spróbuj użyć starej wersji: nie może nadpisać decyzji.",
        ],
        "state": "Stan",
        "version": "Wersja",
        "reason": "Uzasadnienie działania",
        "title_label": "Proponowana zmiana",
        "proposal": "Co ma się zmienić?",
        "edit": "Zapisz szkic",
        "submit": "Przekaż do oceny",
        "approve": "Zatwierdź",
        "reject": "Odrzuć",
        "revise": "Przywróć do szkicu",
        "history": "Historia decyzji",
        "export": "Pobierz raport JSON",
        "stale": "Spróbuj podjąć decyzję na wcześniejszej wersji",
        "stale_note": "Rzeczywiste polecenie ze starą wersją zgłoszenia. Po podjęciu decyzji serwer powinien je odrzucić bez dodania zdarzenia.",
        "closed": "Decyzja jest zamknięta. Sprawdź raport lub rozpocznij nowy scenariusz.",
        "readonly": "Ta rola może przeglądać historię i pobierać raport, ale nie może zmieniać zgłoszenia.",
        "switch_hint": "Przełącz się na drugiego uczestnika, aby kontynuować. Uprawnienia sprawdza serwer.",
        "saved": "Serwer zapisał działanie.",
        "replayed": "To samo polecenie, to samo potwierdzenie. Nie powstało drugie zdarzenie.",
        "error": "Działanie nie zostało potwierdzone",
        "back": "Wróć do aktualnego zgłoszenia",
        "retry": "Ponów to samo polecenie",
        "retained": "Przesłana treść została zachowana poniżej. Sprawdź ją przed ponowieniem. Stara wersja wymaga ponownej oceny, a nie wysłania w ciemno.",
        "unknown": "Odpowiedź bazy jest niedostępna. Wynik może być nieznany. Ponów ten sam klucz polecenia; nie twórz nowego.",
        "expired": "To tymczasowe środowisko wygasło. Rozpocznij nowy fikcyjny scenariusz.",
        "quota": "Demo osiągnęło tymczasowy limit bezpieczeństwa. Spróbuj ponownie później.",
        "default_title": "Kieruj niedopasowane dane rozliczeniowe do sprawdzenia",
        "default_proposal": "Scenariusz fikcyjny: aktualizacje rozliczeń bez dopasowanego klienta trafiają do kolejki wyjątków. Operator sprawdza mapowanie przed zatwierdzeniem aktualizacji. Ta aplikacja zapisuje decyzję; nie łączy się z systemem rozliczeń.",
        "default_reason": "Sprawdzenie fikcyjnej reguły przed zatwierdzeniem zmiany.",
        "source": "Kod źródłowy i odtwarzalne testy",
        "next": "Trudno zapanować nad procesem w firmie?",
        "contact": "Opisz problem",
        "receipt": "Potwierdzenie serwera",
        "expiry": "Środowisko wygasa",
        "codes": {
            "STALE_VERSION": "Inna decyzja zmieniła już tę wersję. Twoje działanie jej nie nadpisało.",
            "READ_ONLY_ROLE": "Audytor nie może zmieniać zgłoszenia.",
            "REVIEWER_REQUIRED": "Decyzję musi podjąć inny uczestnik z rolą zatwierdzającą.",
            "SELF_REVIEW_FORBIDDEN": "Wnioskodawca nie może zatwierdzić własnej zmiany.",
            "INVALID_TRANSITION": "To działanie nie jest dostępne w obecnym stanie.",
            "REASON_REQUIRED_10_TO_500": "Podaj uzasadnienie o długości od 10 do 500 znaków.",
            "INVALID_TITLE": "Tytuł musi zawierać od 5 do 120 znaków.",
            "INVALID_PROPOSAL": "Opis musi zawierać od 5 do 4000 znaków.",
            "INVALID_COMMAND": "Nie udało się zweryfikować polecenia.",
            "NOT_FOUND": "To zgłoszenie nie jest dostępne w Twoim środowisku.",
            "COMMAND_KEY_CONFLICT": "Ten klucz polecenia jest już przypisany do innej treści.",
        },
    },
}
