# Generated by Django 5.2.17 on 2026-10-05 21:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("proposal", models.TextField(max_length=4000)),
                ("state", models.CharField(default="DRAFT", max_length=12)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="desk.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("requester", "Requester"),
                            ("reviewer", "Reviewer"),
                            ("auditor", "Auditor"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="desk.team"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "user"), name="one_team_role"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("role__in", ["requester", "reviewer", "auditor"])
                        ),
                        name="known_role",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actor_name", models.CharField(max_length=150)),
                ("actor_role", models.CharField(max_length=12)),
                ("command_id", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=12)),
                ("version", models.PositiveIntegerField()),
                ("before_state", models.CharField(max_length=12)),
                ("after_state", models.CharField(max_length=12)),
                ("reason", models.CharField(max_length=500)),
                ("snapshot", models.JSONField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="desk.changerequest",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="desk.team"
                    ),
                ),
            ],
            options={
                "ordering": ["version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "version"), name="one_event_per_version"
                    ),
                    models.UniqueConstraint(
                        fields=("team", "actor", "command_id"),
                        name="one_command_per_actor_team",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["team", "state", "updated_at"],
                name="desk_change_team_id_4f57b3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED"])
                ),
                name="known_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="changerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="positive_version"
            ),
        ),
    ]
